# Pré-processamento

## 0) Base de Dados (Substituir com os dados da Sarah)

In [ ]:
# 10 Frases da base de dados do parceiro, usadas inicialmente para testes, antes de integrar com o resto do trabalho do grupo!
# Substituir com os dados da Sarah!
textos = [
    """
    Como faço para fazer depósito
    Já fiz o cadastro na Brastel remit
    """,
    """
    bom dia preciso enviar novamente 970,00 reais, qual valor em ienes por favor???
    """,
    """
    Boa tarde
    Gostaria de saber a cotação pra 30,000¥ com a taxa, por favor 🙏
    """,
    """
    Quero fazer remessa para o Brasil
    Como faço?
    Desse novo aplicativo ainda não usei
    """,
    """
    250 reais
    Quanto tenho depositar no correio
    Por favor
    """,
    """
    Oi
    Boa tarde
    Para chegar no brasil 982 reais quanto tenho que mandar?
    """,
    """
    Como posso me inscrever no serviço de remessa?
    """,
    """
    Boa noite preciso mandar 520 reais para o Brasil quanto seria em yen
    """,
    """
    Quanto tempo levará para o beneficiário receber o dinheiro?
    """,
    """
    Qual procedimento para abrir,cadastrar conta?
    """
]

## 1) Reconhecimento de Nomes de Entidades (substituir por quem implementou, de fato) - Carneiro

Se quiser, escreve uma pequena descrição do que essa parte faz, embasando com uma referência da NET. ([Fonte]())

In [ ]:
#Colocar código do Carneiro

### 1.1) Resultados Esperados (substituir se acha que faz sentido)


```
['Como', 'faço', 'para', 'fazer', 'depósito', 'Já', 'fiz', 'o', 'cadastro', 'na', 'Brastel', 'remit']
['bom', 'dia', 'preciso', 'enviar', 'novamente', '970,00', 'reais', ',', 'qual', 'valor', 'em', 'ienes', 'por', 'favor', '?', '?', '?']
['Boa', 'tarde', 'Gostaria', 'de', 'saber', 'a', 'cotação', 'pra', '30,000', '¥', 'com', 'a', 'taxa', ',', 'por', 'favor', '🙏']
['Quero', 'fazer', 'remessa', 'para', 'o', 'Brasil', 'Como', 'faço', '?', 'Desse', 'novo', 'aplicativo', 'ainda', 'não', 'usei']
['250', 'reais', 'Quanto', 'tenho', 'depositar', 'no', 'correio', 'Por', 'favor']
['Oi', 'Boa', 'tarde', 'Para', 'chegar', 'no', 'brasil', '982', 'reais', 'quanto', 'tenho', 'que', 'mandar', '?']
['Como', 'posso', 'me', 'inscrever', 'no', 'serviço', 'de', 'remessa', '?']
['Boa', 'noite', 'preciso', 'mandar', '520', 'reais', 'para', 'o', 'Brasil', 'quanto', 'seria', 'em', 'yen']
['Quanto', 'tempo', 'levará', 'para', 'o', 'beneficiário', 'receber', 'o', 'dinheiro', '?']
['Qual', 'procedimento', 'para', 'abrir', ',', 'cadastrar', 'conta', '?']

```

### 1.2) Resultados Obtidos

In [ ]:
# Colocar chamada para a função, se quiser seguindo o seguinte padrão:

print(f"Frase {p+1}: {tokens}")

Frase 1: ['Como', 'faço', 'para', 'fazer', 'depósito', 'Já', 'fiz', 'o', 'cadastro', 'na', 'Brastel', 'remit']
Frase 2: ['bom', 'dia', 'preciso', 'enviar', 'novamente', '970,00', 'reais', ',', 'qual', 'valor', 'em', 'ienes', 'por', 'favor', '?', '?', '?']
Frase 3: ['Boa', 'tarde', 'Gostaria', 'de', 'saber', 'a', 'cotação', 'pra', '30,000', '¥', 'com', 'a', 'taxa', ',', 'por', 'favor', '🙏']
Frase 4: ['Quero', 'fazer', 'remessa', 'para', 'o', 'Brasil', 'Como', 'faço', '?', 'Desse', 'novo', 'aplicativo', 'ainda', 'não', 'usei']
Frase 5: ['250', 'reais', 'Quanto', 'tenho', 'depositar', 'no', 'correio', 'Por', 'favor']
Frase 6: ['Oi', 'Boa', 'tarde', 'Para', 'chegar', 'no', 'brasil', '982', 'reais', 'quanto', 'tenho', 'que', 'mandar', '?']
Frase 7: ['Como', 'posso', 'me', 'inscrever', 'no', 'serviço', 'de', 'remessa', '?']
Frase 8: ['Boa', 'noite', 'preciso', 'mandar', '520', 'reais', 'para', 'o', 'Brasil', 'quanto', 'seria', 'em', 'yen']
Frase 9: ['Quanto', 'tempo', 'levará', 'para', 'o', 

## 2) Tokenização (substituir por quem implementou, de fato) - Sarah

A Tokenização consiste no processo de divisão de um texto em partes menores, tokens, sejam elas palavras, caracteres ou até frases, de forma que o modelo de LLM possa processar e manipular os tokens com os algoritmos. Esse processo é a primeira etapa do treinamento do modelo e essencial para o resultado das outras etapas. ([Fonte](https://learn.microsoft.com/pt-br/dotnet/ai/conceptual/understanding-tokens))

In [ ]:
import re

def tokenizar(texto):
    texto = re.sub(r'\s+', ' ', texto) #substitui mais de um espaço por um único
    tokens = re.findall(r'\d+,\d+|\d+\.\d+|\w+|[^\w\s]', texto) #separa as palavras das pontuações e mantém números decimais ou com ponto juntos (estava errado sem os "d" - nº)
    return tokens

### 2.1) Resultados Esperados (substituir se acha que faz sentido)


```
['Como', 'faço', 'para', 'fazer', 'depósito', 'Já', 'fiz', 'o', 'cadastro', 'na', 'Brastel', 'remit']
['bom', 'dia', 'preciso', 'enviar', 'novamente', '970,00', 'reais', ',', 'qual', 'valor', 'em', 'ienes', 'por', 'favor', '?', '?', '?']
['Boa', 'tarde', 'Gostaria', 'de', 'saber', 'a', 'cotação', 'pra', '30,000', '¥', 'com', 'a', 'taxa', ',', 'por', 'favor', '🙏']
['Quero', 'fazer', 'remessa', 'para', 'o', 'Brasil', 'Como', 'faço', '?', 'Desse', 'novo', 'aplicativo', 'ainda', 'não', 'usei']
['250', 'reais', 'Quanto', 'tenho', 'depositar', 'no', 'correio', 'Por', 'favor']
['Oi', 'Boa', 'tarde', 'Para', 'chegar', 'no', 'brasil', '982', 'reais', 'quanto', 'tenho', 'que', 'mandar', '?']
['Como', 'posso', 'me', 'inscrever', 'no', 'serviço', 'de', 'remessa', '?']
['Boa', 'noite', 'preciso', 'mandar', '520', 'reais', 'para', 'o', 'Brasil', 'quanto', 'seria', 'em', 'yen']
['Quanto', 'tempo', 'levará', 'para', 'o', 'beneficiário', 'receber', 'o', 'dinheiro', '?']
['Qual', 'procedimento', 'para', 'abrir', ',', 'cadastrar', 'conta', '?']

```

### 2.2) Resultados Obtidos

In [ ]:
# Segmentar tokens
teste_tokenizacao = [tokenizar(texto) for texto in textos]

# Exibir resultados da tokenização
for i, tokens in enumerate(teste_tokenizacao):
    print(f"Frase {i+1}: {tokens}")

Frase 1: ['Como', 'faço', 'para', 'fazer', 'depósito', 'Já', 'fiz', 'o', 'cadastro', 'na', 'Brastel', 'remit']
Frase 2: ['bom', 'dia', 'preciso', 'enviar', 'novamente', '970,00', 'reais', ',', 'qual', 'valor', 'em', 'ienes', 'por', 'favor', '?', '?', '?']
Frase 3: ['Boa', 'tarde', 'Gostaria', 'de', 'saber', 'a', 'cotação', 'pra', '30,000', '¥', 'com', 'a', 'taxa', ',', 'por', 'favor', '🙏']
Frase 4: ['Quero', 'fazer', 'remessa', 'para', 'o', 'Brasil', 'Como', 'faço', '?', 'Desse', 'novo', 'aplicativo', 'ainda', 'não', 'usei']
Frase 5: ['250', 'reais', 'Quanto', 'tenho', 'depositar', 'no', 'correio', 'Por', 'favor']
Frase 6: ['Oi', 'Boa', 'tarde', 'Para', 'chegar', 'no', 'brasil', '982', 'reais', 'quanto', 'tenho', 'que', 'mandar', '?']
Frase 7: ['Como', 'posso', 'me', 'inscrever', 'no', 'serviço', 'de', 'remessa', '?']
Frase 8: ['Boa', 'noite', 'preciso', 'mandar', '520', 'reais', 'para', 'o', 'Brasil', 'quanto', 'seria', 'em', 'yen']
Frase 9: ['Quanto', 'tempo', 'levará', 'para', 'o', 

## 3) Remoção de Stop Words (substituir por quem implementou, de fato)


A etapa de remoção de Stop Words é um processo de refinamento e eliminação de palavras irrelevantes para o processamento do modelo de LLM, ao consultar em uma lista de palavras irrelevantes no idioma em questão. Assim, a dimensionalidade do problema é diminuída e a eficiência do modelo aumentada com a eliminação de palavras irrelevantes, como "a", "e", "de". ([Fonte](https://fineproxy.org/pt/wiki/stopword-removal/#:~:text=A%20remo%C3%A7%C3%A3o%20de%20palavras%20de,automatizado%20e%20classifica%C3%A7%C3%A3o%20de%20textos.))

In [ ]:
import nltk

# Baixa a lista de stop words
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def remover_stop_words(texto):
    # Lista de stop words em português
    stop_words = set(stopwords.words('portuguese'))
    # Tokeniza o texto
    tokens = tokenizar(texto)
    # Filtra as stop words
    tokens_filtrados = [token for token in tokens if token.lower() not in stop_words]

    return tokens_filtrados

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


### 3.1) Resultados Esperados

```
['faço', 'fazer', 'depósito', 'fiz', 'cadastro', 'Brastel', 'remit']
['bom', 'dia', 'preciso', 'enviar', 'novamente', '970,00', 'reais', ',', 'valor', 'ienes', 'favor', '?', '?', '?']
['Boa', 'tarde', 'Gostaria', 'saber', 'cotação', 'pra', '30,000', '¥', 'taxa', ',', 'favor', '🙏']
['Quero', 'fazer', 'remessa', 'Brasil', 'faço', '?', 'Desse', 'novo', 'aplicativo', 'ainda', 'usei']
['250', 'reais', 'Quanto', 'depositar', 'correio', 'favor']
['Oi', 'Boa', 'tarde', 'chegar', 'brasil', '982', 'reais', 'quanto', 'mandar', '?']
['posso', 'inscrever', 'serviço', 'remessa', '?']
['Boa', 'noite', 'preciso', 'mandar', '520', 'reais', 'Brasil', 'quanto', 'yen']
['Quanto', 'tempo', 'levará', 'beneficiário', 'receber', 'dinheiro', '?']
['procedimento', 'abrir', ',', 'cadastrar', 'conta', '?']
```

### 3.2) Resultados Obtidos

In [ ]:
# Exibir resultados da remoção de stop words
x = -1
for texto in textos:
    x += 1
    tokens_sem_stop_words = remover_stop_words(texto)
    print(f"Frase {x+1}: {tokens_sem_stop_words}")

Frase 1: ['faço', 'fazer', 'depósito', 'fiz', 'cadastro', 'Brastel', 'remit']
Frase 2: ['bom', 'dia', 'preciso', 'enviar', 'novamente', '970,00', 'reais', ',', 'valor', 'ienes', 'favor', '?', '?', '?']
Frase 3: ['Boa', 'tarde', 'Gostaria', 'saber', 'cotação', 'pra', '30,000', '¥', 'taxa', ',', 'favor', '🙏']
Frase 4: ['Quero', 'fazer', 'remessa', 'Brasil', 'faço', '?', 'Desse', 'novo', 'aplicativo', 'ainda', 'usei']
Frase 5: ['250', 'reais', 'Quanto', 'depositar', 'correio', 'favor']
Frase 6: ['Oi', 'Boa', 'tarde', 'chegar', 'brasil', '982', 'reais', 'quanto', 'mandar', '?']
Frase 7: ['posso', 'inscrever', 'serviço', 'remessa', '?']
Frase 8: ['Boa', 'noite', 'preciso', 'mandar', '520', 'reais', 'Brasil', 'quanto', 'yen']
Frase 9: ['Quanto', 'tempo', 'levará', 'beneficiário', 'receber', 'dinheiro', '?']
Frase 10: ['procedimento', 'abrir', ',', 'cadastrar', 'conta', '?']


## 4) Lematização

A Lematização é o processo de extrair o infinitivo dos verbos, de forma que haja uma padronização na utilização das palavras. Isso é importante para a rede reconhecer de forma mais simples os padrões entre os tokens. ([Fonte](https://blog.bitso.com/pt-br/criptomoedas/diferenca-entre-tokenizacao-e-lematizacao#:~:text=Lematiza%C3%A7%C3%A3o%20%C3%A9%20um%20tipo%20de,fim%20de%20simplificar%20a%20palavra.))

In [ ]:
!pip install spacy
!python -m spacy download pt_core_news_sm

import spacy

nlp = spacy.load('pt_core_news_sm')

def lematizar(texto):
    texto = ' '.join(texto)  # Fundamental para preservar o formato de entrada
    doc = nlp(texto)
    token_lematizado = [token.lemma_ for token in doc]  # Aplica a lematização em cada token

    return token_lematizado

# Caso os dados da Sarah venham em em colunas de um dataframe:

# def lematizar(texto):
#     texto = ' '.join(texto)  # Fundamental para preservar o formato de entrada
#     doc = nlp(texto)
#     token_lematizado = [token.lemma_ for token in doc]  # Aplica a lematização em cada token

#     return token_lematizado

# # Aplicando a lematização às colunas 'Pergunta' e 'Resposta'
# chats_clients['Pergunta_Lematizada'] = chats_clients['Pergunta'].apply(lematizar)
# chats_clients['Resposta_Lematizada'] = chats_clients['Resposta'].apply(lematizar)

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.0/13.0 MB 53.5 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('pt_core_news_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


### 4.1) Resultados Esperados (substituir pelo conjunto de dados reais)

```
['fazer', 'fazer', 'depósito', 'fazer', 'cadastro', 'Brastel', 'remit']
['bom', 'dia', 'precisar', 'enviar', 'novamente', '970,00', 'real', ',', 'valor', 'iene', 'favor', '?', '?', '?']
['Boa', 'tarde', 'Gostar', 'saber', 'cotação', 'pra', '30,000', '¥', 'taxa', ',', 'favor', '🙏']
['querer', 'fazer', 'remessa', 'Brasil', 'fazer', '?', 'Desse', 'novo', 'aplicativo', 'ainda', 'usei']
['250', 'real', 'quanto', 'depositar', 'correio', 'favor']
['Oi', 'Boa', 'tarde', 'chegar', 'Brasil', '982', 'real', 'quanto', 'mandar', '?']
['poder', 'inscrever', 'serviço', 'remessa', '?']
['Boa', 'noite', 'precisar', 'mandar', '520', 'real', 'Brasil', 'quanto', 'yen']
['quanto', 'tempo', 'levar', 'beneficiário', 'receber', 'dinheiro', '?']
['procedimento', 'abrir', ',', 'cadastrar', 'conta', '?']
```

### 4.2) Resultados Obtidos

In [ ]:
y = -1
for texto in textos:
    y += 1
    tokens_sem_stop_words = remover_stop_words(texto)
    tokens_lematizados = lematizar(tokens_sem_stop_words)
    print(f"Frase {y+1}: {tokens_lematizados}")

#Caso seja utilizado um DF, printar da seguinte forma:
# Exibir o DataFrame com as colunas lematizadas
#print(chats_clients[['Pergunta_Lematizada', 'Resposta_Lematizada']])

Frase 1: ['fazer', 'fazer', 'depósito', 'fiz', 'cadastro', 'Brastel', 'remitr']
Frase 2: ['bom', 'dia', 'preciso', 'enviar', 'novamente', '970,00', 'real', ',', 'valor', 'iene', 'favor', '?', '?', '?']
Frase 3: ['Boa', 'tarde', 'Gostaria', 'saber', 'cotação', 'pra', '30,000', '¥', 'taxa', ',', 'favor', '🙏']
Frase 4: ['querer', 'fazer', 'remesso', 'Brasil', 'fazer', '?', 'de esse', 'novo', 'aplicativo', 'ainda', 'usei']
Frase 5: ['250', 'real', 'quanto', 'depositar', 'correio', 'favor']
Frase 6: ['Oi', 'Boa', 'tarde', 'chegar', 'Brasil', '982', 'real', 'quanto', 'mandar', '?']
Frase 7: ['poder', 'inscrever', 'serviço', 'remesso', '?']
Frase 8: ['Boa', 'noite', 'preciso', 'mandar', '520', 'real', 'Brasil', 'quanto', 'yen']
Frase 9: ['quanto', 'tempo', 'levar', 'beneficiário', 'receber', 'dinheiro', '?']
Frase 10: ['procedimento', 'abrir', ',', 'cadastrar', 'conta', '?']


Esses resultados não estão perfeitamente equivalentes com o esperado por possíveis limitações da biblioteca utilizada.

## 5) Stemming

O stemming é o processo de remover sufixos e prefixos, deixando os verbos em sua forma base (raiz), de forma semelhante à Lematização. O stemming é considerado um processo mais agressivo que a Lematização, então pode gerar radicais que não são palavras reais. [Fonte](https://www.alura.com.br/artigos/lemmatization-vs-stemming-quando-usar-cada-um)

In [ ]:
# df_palavras['nltk_stemmer'] = [stemmer.stem(palavra) for palavra in df_palavras['Original']]
# df_palavras

nltk.download('rslp')
from nltk.stem import RSLPStemmer

def aplicar_stemming(tokens):
    stemmer = RSLPStemmer()
    stems = [stemmer.stem(token) for token in tokens]
    return stems

# Se precisar aplicar em um DF:
# def aplicar_stemming(tokens):
#     stemmer = RSLPStemmer()
#     stems = [stemmer.stem(token) for token in tokens]
#     return stems

# # Aplicando o stemming às colunas 'Pergunta' e 'Resposta'
# chats_clients['Pergunta_Stemmed'] = chats_clients['Pergunta'].apply(aplicar_stemming)
# chats_clients['Resposta_Stemmed'] = chats_clients['Resposta'].apply(aplicar_stemming)

[nltk_data] Downloading package rslp to /root/nltk_data...
[nltk_data]   Package rslp is already up-to-date!


### 5.1) Resultados Esperados

```
['fazer', 'fazer', 'depósito', 'fazer', 'cadastro', 'Brastel', 'remit']
['bom', 'dia', 'precisar', 'enviar', 'novamente', '970,00', 'real', ',', 'valor', 'iene', 'favor', '?', '?', '?']
['Boa', 'tarde', 'Gostar', 'saber', 'cotação', 'pra', '30,000', '¥', 'taxa', ',', 'favor', '🙏']
['querer', 'fazer', 'remessa', 'Brasil', 'fazer', '?', 'Desse', 'novo', 'aplicativo', 'ainda', 'usei']
['250', 'real', 'quanto', 'depositar', 'correio', 'favor']
['Oi', 'Boa', 'tarde', 'chegar', 'Brasil', '982', 'real', 'quanto', 'mandar', '?']
['poder', 'inscrever', 'serviço', 'remessa', '?']
['Boa', 'noite', 'precisar', 'mandar', '520', 'real', 'Brasil', 'quanto', 'yen']
['quanto', 'tempo', 'levar', 'beneficiário', 'receber', 'dinheiro', '?']
['procedimento', 'abrir', ',', 'cadastrar', 'conta', '?']
```

### 5.2) Resultados Obtidos

In [ ]:
w = -1
for texto in textos:
    w += 1
    tokens_sem_stop_words = remover_stop_words(texto)
    tokens_com_stemming = aplicar_stemming(tokens_sem_stop_words)
    print(f"Frase {w+1}: {tokens_com_stemming}")

# Se precisar printar o df:
# Exibir o DataFrame com as colunas após o stemming
# print(chats_clients[['Pergunta_Stemmed', 'Resposta_Stemmed']])

Frase 1: ['faç', 'faz', 'depósit', 'fiz', 'cadastr', 'brastel', 'remit']
Frase 2: ['bom', 'dia', 'precis', 'envi', 'nov', '970,00', 'real', ',', 'val', 'ien', 'favor', '?', '?', '?']
Frase 3: ['boa', 'tard', 'gost', 'sab', 'cot', 'pra', '30,000', '¥', 'tax', ',', 'favor', '🙏']
Frase 4: ['quer', 'faz', 'remess', 'brasil', 'faç', '?', 'dess', 'nov', 'aplic', 'aind', 'use']
Frase 5: ['250', 'real', 'quant', 'depos', 'correi', 'favor']
Frase 6: ['oi', 'boa', 'tard', 'cheg', 'brasil', '982', 'real', 'quant', 'mand', '?']
Frase 7: ['poss', 'inscrev', 'serviç', 'remess', '?']
Frase 8: ['boa', 'noit', 'precis', 'mand', '520', 'real', 'brasil', 'quant', 'yen']
Frase 9: ['quant', 'temp', 'lev', 'benefici', 'receb', 'dinh', '?']
Frase 10: ['proced', 'abr', ',', 'cadastr', 'cont', '?']


Com isso, vê-se que os resultados obtidos com o Stemming não são nem próximos do satisfatório, sendo, portanto, a escolha da Lematização uma melhor abordagem para nosso problema

## 6) Pipeline completa

A fim de simplificar o pré-processamento, junta-se todos os processos empregados na seguite função até então (em desenvolvimento)

In [ ]:
def pre_processamento(texto):
    #substituir pelas funções que foram implementadas de outros membros do grupo, se achar que faz sentido!
    tokens_sem_stop_words_finais = remover_stop_words(texto) #substituir pela função de quem fez a remoção do stop words
    tokens_lematizados_finais = lematizar(tokens_sem_stop_words_finais)
    return tokens_lematizados_finais


### 6.1) Resultados Esperados

```
['fazer', 'fazer', 'depósito', 'fazer', 'cadastro', 'Brastel', 'remit']
['bom', 'dia', 'precisar', 'enviar', 'novamente', '970,00', 'real', ',', 'valor', 'iene', 'favor', '?', '?', '?']
['Boa', 'tarde', 'Gostar', 'saber', 'cotação', 'pra', '30,000', '¥', 'taxa', ',', 'favor', '🙏']
['querer', 'fazer', 'remessa', 'Brasil', 'fazer', '?', 'Desse', 'novo', 'aplicativo', 'ainda', 'usei']
['250', 'real', 'quanto', 'depositar', 'correio', 'favor']
['Oi', 'Boa', 'tarde', 'chegar', 'Brasil', '982', 'real', 'quanto', 'mandar', '?']
['poder', 'inscrever', 'serviço', 'remessa', '?']
['Boa', 'noite', 'precisar', 'mandar', '520', 'real', 'Brasil', 'quanto', 'yen']
['quanto', 'tempo', 'levar', 'beneficiário', 'receber', 'dinheiro', '?']
['procedimento', 'abrir', ',', 'cadastrar', 'conta', '?']
```

### 6.2) Resultados Obtidos

In [ ]:
# Aplicando o processamento completo a cada texto
z = -1
for texto in textos:
    z += 1
    textos_finais = pre_processamento(texto)
    print(f"Frase {z+1}: {textos_finais}")

Frase 1: ['fazer', 'fazer', 'depósito', 'fiz', 'cadastro', 'Brastel', 'remitr']
Frase 2: ['bom', 'dia', 'preciso', 'enviar', 'novamente', '970,00', 'real', ',', 'valor', 'iene', 'favor', '?', '?', '?']
Frase 3: ['Boa', 'tarde', 'Gostaria', 'saber', 'cotação', 'pra', '30,000', '¥', 'taxa', ',', 'favor', '🙏']
Frase 4: ['querer', 'fazer', 'remesso', 'Brasil', 'fazer', '?', 'de esse', 'novo', 'aplicativo', 'ainda', 'usei']
Frase 5: ['250', 'real', 'quanto', 'depositar', 'correio', 'favor']
Frase 6: ['Oi', 'Boa', 'tarde', 'chegar', 'Brasil', '982', 'real', 'quanto', 'mandar', '?']
Frase 7: ['poder', 'inscrever', 'serviço', 'remesso', '?']
Frase 8: ['Boa', 'noite', 'preciso', 'mandar', '520', 'real', 'Brasil', 'quanto', 'yen']
Frase 9: ['quanto', 'tempo', 'levar', 'beneficiário', 'receber', 'dinheiro', '?']
Frase 10: ['procedimento', 'abrir', ',', 'cadastrar', 'conta', '?']


Esses resultados não estão perfeitamente equivalentes com o esperado por possíveis limitações da biblioteca utilizada.